<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
        <AssemblyName>DrifterApps.Seeds.FluentResult.Tests</AssemblyName>
        <RootNamespace>FluentResult.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\FluentResult.FluentAssertions\FluentResult.FluentAssertions.csproj"/>
        <ProjectReference Include="..\..\src\FluentResult\FluentResult.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="FluentAssertions.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
        <PackageReference Include="xunit.v3.runner.console">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="ResultExtensions.AsyncTests.cs">
            <DependentUpon>ResultExtensionsTests.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
